name: dangple_time_picker
description: "Time format tailored to the locale."
version: 1.0.0
repository: https://github.com/dangple-kr/dangple-time-picker
homepage: https://github.com/dangple-kr

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
